# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Charles Leverington
email: charles.leverington@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  <ul>
    <li>If it can be written, it is known.</li>
    <li>If it is known, it is reproducible.</li>
    <li>If it isn't documented, it doesn't exist.</li>
  </ul>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cleverington.github.io/" # the base hostname & protocol for your site
twitter_username: c_leverington
github_username:  cleverington
drupal_username: cleverington
# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
# SEO
twitter:
  username: c_leverington
sass:
  sass_dir: _sass
theme: jekyll-theme-time-machine
plugins:
  - jekyll-assets
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag