# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Charles Leverington
email: charles.leverington@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  * If it can be written, it is known.
  * If it is known, it is reproducible.
  If it isn't documented, it doesn't exist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cleverington.github.io/" # the base hostname & protocol for your site
twitter_username: c_leverington
github_username:  cleverington

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
